### ISSUE TITLE
Force a server-side rebuild?

### ISSUE THREAD

**Issue by denilsonsa** [djacquel/JekyllDoc#1]
It seems the latest commit was from 2015-12-21, and [since Feb 2016 GitHub Pages has been running Jekyll 3.0](https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0). That means [several tests](http://jekyll.pygmeeweb.com/tests/) that were previously broken are now (hopefully) fixed. In special, `ceil` and `floor` will finally work.

So, could you push any commit to this repository, just to force it to rebuild? Thanks!

**Comment by denilsonsa** [comment]
As a bonus, you could include a link to https://pages.github.com/versions/ at [`footer.html`](https://github.com/djacquel/JekyllDoc/blob/gh-pages/_includes/footer.html). That way, we can compare the versions from when the page was generated to the latest versions.

**Comment by djacquel** [comment]
Hoops ! someone who takes care of my work ! Great !
I'm not alone !!!
I'm waiting for your PRs.
